#!/usr/bin/env python

import click
from tsugou import *


@click.group()
def tsu():
    pass


@tsu.command()
@click.argument("template", required=False)
def init(template):
    """
    Initialize the current diretory as a tsu project
    """

    if template:
        print_error("Not implemented yet")

    if os.path.exists(tsu_folder_name):
        print_error(f"{tsu_folder_name} project already exists")

    os.mkdir(tsu_folder_name)


@tsu.command()
def test():
    x = Commit("1", "This is a test", "kai", "0", ["", "", ""])

    x.show()

if __name__ == "__main__":
    print(user_home)
    tsu()
